ALTER TABLE "StockItem" ADD COLUMN IF NOT EXISTS "locationBalances" JSONB;

ALTER TABLE "StockTransfer" ADD COLUMN IF NOT EXISTS "kind" TEXT NOT NULL DEFAULT 'sku';
ALTER TABLE "StockTransfer" ADD COLUMN IF NOT EXISTS "stockId" TEXT;
ALTER TABLE "StockTransfer" ADD COLUMN IF NOT EXISTS "fromLocation" TEXT;
ALTER TABLE "StockTransfer" ADD COLUMN IF NOT EXISTS "toLocation" TEXT;
