#!/bin/bash
# Local PostgreSQL for mesa-api (Docker, localhost-only, persistent volume).
# Run on the CyberPanel server as root:
#   bash deploy/cyberpanel/install-postgres.sh
#
# Optional env:
#   POSTGRES_USER=mesa
#   POSTGRES_DB=mesa
#   POSTGRES_PASSWORD=...     # auto-generated if unset
#   POSTGRES_PORT=5432        # bound to 127.0.0.1 only
#   SECRETS_DIR=/home/restaurant-pos.isarva.in/secrets

set -euo pipefail

POSTGRES_USER="${POSTGRES_USER:-mesa}"
POSTGRES_DB="${POSTGRES_DB:-mesa}"
POSTGRES_PORT="${POSTGRES_PORT:-5432}"
CONTAINER_NAME="${CONTAINER_NAME:-mesa-postgres}"
VOLUME_NAME="${VOLUME_NAME:-mesa-postgres-data}"
SECRETS_DIR="${SECRETS_DIR:-/home/restaurant-pos.isarva.in/secrets}"
CREDS_FILE="${SECRETS_DIR}/postgres.env"

log() { echo "[install-postgres] $*"; }

if [ "$(id -u)" -ne 0 ]; then
  echo "Run as root: sudo bash $0"
  exit 1
fi

if ! command -v docker >/dev/null 2>&1; then
  echo "ERROR: Docker not found. Run deploy/cyberpanel/fix-docker-install.sh first."
  exit 1
fi

if [ -z "${POSTGRES_PASSWORD:-}" ]; then
  if [ -f "${CREDS_FILE}" ]; then
    # shellcheck disable=SC1090
    source "${CREDS_FILE}"
    POSTGRES_PASSWORD="${POSTGRES_PASSWORD:-}"
  fi
fi

if [ -z "${POSTGRES_PASSWORD:-}" ]; then
  POSTGRES_PASSWORD="$(openssl rand -base64 24 | tr -d '/+=' | head -c 32)"
fi

mkdir -p "${SECRETS_DIR}"
chmod 700 "${SECRETS_DIR}"

if docker ps -a --format '{{.Names}}' | grep -qx "${CONTAINER_NAME}"; then
  if docker ps --format '{{.Names}}' | grep -qx "${CONTAINER_NAME}"; then
    log "Container ${CONTAINER_NAME} already running."
  else
    log "Starting existing container ${CONTAINER_NAME}..."
    docker start "${CONTAINER_NAME}"
  fi
else
  log "Creating Postgres 17 container (${CONTAINER_NAME})..."
  docker run -d \
    --name "${CONTAINER_NAME}" \
    --restart unless-stopped \
    -e POSTGRES_USER="${POSTGRES_USER}" \
    -e POSTGRES_PASSWORD="${POSTGRES_PASSWORD}" \
    -e POSTGRES_DB="${POSTGRES_DB}" \
    -p "127.0.0.1:${POSTGRES_PORT}:5432" \
    -v "${VOLUME_NAME}:/var/lib/postgresql/data" \
    postgres:17-alpine
fi

log "Waiting for Postgres to accept connections..."
for i in $(seq 1 30); do
  if docker exec "${CONTAINER_NAME}" pg_isready -U "${POSTGRES_USER}" -d "${POSTGRES_DB}" >/dev/null 2>&1; then
    break
  fi
  sleep 1
done

if ! docker exec "${CONTAINER_NAME}" pg_isready -U "${POSTGRES_USER}" -d "${POSTGRES_DB}" >/dev/null 2>&1; then
  echo "ERROR: Postgres did not become ready in time."
  exit 1
fi

cat >"${CREDS_FILE}" <<EOF
# Generated by install-postgres.sh — keep private
POSTGRES_USER=${POSTGRES_USER}
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_DB=${POSTGRES_DB}
POSTGRES_PORT=${POSTGRES_PORT}
DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@127.0.0.1:${POSTGRES_PORT}/${POSTGRES_DB}?sslmode=disable
DATABASE_ADMIN_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@127.0.0.1:${POSTGRES_PORT}/postgres?sslmode=disable
EOF
chmod 600 "${CREDS_FILE}"

log "Credentials written to ${CREDS_FILE}"
log ""
log "Next steps:"
log "  1. Copy DATABASE_URL / DATABASE_ADMIN_URL into mesa-api/.env"
log "  2. Migrate data: bash deploy/cyberpanel/migrate-from-supabase.sh"
log "     OR fresh schema: cd mesa-api && npx prisma migrate deploy"
log "  3. pm2 restart mesa-api --update-env"
log ""
log "DATABASE_URL=postgresql://${POSTGRES_USER}:****@127.0.0.1:${POSTGRES_PORT}/${POSTGRES_DB}?sslmode=disable"
